// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlrivxntdtewfagrbtry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpscml2eG50ZHRld2ZhZ3JidHJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ5MTQ1MzEsImV4cCI6MjA4MDQ5MDUzMX0.ciu4AOyMt4W5jUQdDH2V1iS0fpWpwHRHylGjrdBnFrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});